FROM golang:latest
MAINTAINER Anshuman Bhartiya <anshuman.bhartiya@gmail.com>

RUN wget https://github.com/lair-framework/api-server/releases/download/v1.1.0/api-server_linux_amd64
RUN chmod +x api-server_linux_amd64
